### PR TITLE
fix: UDP packet checksum computation

### PR DESCRIPTION
**Pull request by noirotm**
Hello,
while trying to solve one of the layers in [Tom Dalling's Data Onion challenge](https://www.tomdalling.com/toms-data-onion/) involving IP packet decoding, I decided to use this crate in order to verify UDP packet checksums. However, I realized it yielded incorrect results.

After reading RFC 768, and having a look at several implementations, I found out that there were two bugs that needed to be fixed for the computation to be correct.

1. RFC 768 states that the checksum is the 16-bit one's complement of the one's complement sum of pseudo-header, UDP header, and data, therefore the initial value of `0xffffu32` is erroneous, and should be 0 instead.

2. If payload data length is odd, the last call to `buffer.read_u16::<BigEndian>()` will fail entirely, causing the last byte of the payload to be ignored. Since that failure does not advance the cursor's pointer, we can try again and read a u8 instead, then pad it to 16-bit and use it in the checksum.

Apart from these issues, this code has been a great help to me, so thank you for releasing this 😃.

Regards,
Marc

PS: examples of implementations I looked at:
http://www.rohitab.com/discuss/topic/35831-udp-header-checksum-calculation/
https://github.com/shard013/DataOnion/blob/master/DataOnion/Layers/Layer4.cs#L75

### CODE REVIEW

**Comment by noirotm** [comment]
Just realized this repository uses tabs for indentation.

To be honest, I believe you might want to try relying on rustfmt, as it has really spoiled me regarding code formatting and the lack of need for a coding convention to be enforced when contributing to a Rust project.

If you are really intent on using tabs vs. spaces, you may provide a `.rustfmt.toml` file at the root of your project and use the following contents ([reference here](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)):

    hard_tabs = true

This may also be enforced by the CI as explained [here](https://medium.com/@ag_dubs/enforcing-style-in-ci-for-rust-projects-18f6b09ec69d), for example.

**Comment by meh** [comment]
Thanks! And sorry for the rookie mistake.

Is rustfmt decent now? When I was using it ~3 years ago it was more trouble than help so I stopped using it, how's the situation with formatting of macros and such?

**Comment by noirotm** [comment]
My use of macros has been pretty limited so far, so I can't really tell how rustfmt works in that regard.

It would appear as though there are [flags to control macro formatting](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_macro_matchers) which were added in 2018.

My experience with rustfmt is that it's doing mostly ok. A notable exception is when using libraries such as clap. It then looks like [this](https://github.com/noirotm/fishr/blob/master/src/main.rs#L8), a little bit too spacious for my taste 😃.

**Comment by ssrlive** [comment]
After I use this crate, when I send an even-length UDP packet, the data is correct. But when I send an odd-length UDP packet, the data packet is wrong. What are your test results?

**Comment by noirotm** [comment]
@ssrlive I believe that while my fix was merged, it was never released to crates.io.

The latest version is 0.1.4, but the code found at https://docs.rs/packet/0.1.4/src/packet/udp/mod.rs.html#30 still looks like the old code before this PR was merged.

It looks like the released crate version is out-of-sync with the source code in this repository, as the Cargo.toml file here on Github still specifies 0.1.2.

@meh Could you please clarify the status of the project?

It turns out that the Rust 1.80 release broke my fix as well as the one for TCP, so the current HEAD of the project here is broken. I applied a local fix here: https://github.com/noirotm/data-onion/commit/f70f4a95f90838842638488b463c2fc0db689460

I'd like to propose a PR to fix the checksum functions, but:
- there is an additional failing test for the TCP packet builder which I don't really have time to try to fix
- if this crate is abandoned, or if there are code changes which are published on crates.io but not here, I am not convinced it is worth for me to continue contributing, and I'll look for alternatives instead.

While I appreciate the work which has been put into this crate, it is unfortunately not usable in its current state.

**Pull request merged**
